# Generated by Django 4.1.2 on 2022-11-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpractice', '0002_remove_order_id_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
