# Generated by Django 4.1.2 on 2022-11-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abpractice', '0002_alter_customuser_address_alter_customuser_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mailing_address',
        ),
    ]
