# Generated by Django 4.1.2 on 2022-11-23 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abpractice', '0005_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.CreateModel(
            name='Placed_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=300)),
                ('product_description', models.CharField(max_length=300)),
                ('product_price', models.IntegerField()),
                ('product_category', models.CharField(max_length=300)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='abpractice.order')),
            ],
        ),
    ]
