# Generated by Django 4.1.2 on 2022-11-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abpractice', '0006_remove_order_product_placed_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placed_order',
            old_name='order_id',
            new_name='order',
        ),
    ]
