# Generated by Django 4.1.2 on 2022-11-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abpractice', '0009_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('A', 'active'), ('I', 'inactive'), ('C', 'canceled')], default='A', max_length=30),
        ),
    ]
